// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2ok8Yk2zLme11-RU6tTq2tLTaRyktteo',
    appId: '1:604640462956:web:c03f5dd656ca68bef47049',
    messagingSenderId: '604640462956',
    projectId: 'scmu-2ac12',
    authDomain: 'scmu-2ac12.firebaseapp.com',
    databaseURL: 'https://scmu-2ac12-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scmu-2ac12.appspot.com',
    measurementId: 'G-JTETTFYHG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa7qe_7MS-QlWHWBrkFyredfbT9PfSocE',
    appId: '1:604640462956:android:600cfc2c81e3faa7f47049',
    messagingSenderId: '604640462956',
    projectId: 'scmu-2ac12',
    databaseURL: 'https://scmu-2ac12-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scmu-2ac12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9snTD4pSB4_w3drjoPhssi7Y5g_0hGsY',
    appId: '1:604640462956:ios:00cce6034610ca79f47049',
    messagingSenderId: '604640462956',
    projectId: 'scmu-2ac12',
    databaseURL: 'https://scmu-2ac12-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scmu-2ac12.appspot.com',
    iosBundleId: 'com.example.scmu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9snTD4pSB4_w3drjoPhssi7Y5g_0hGsY',
    appId: '1:604640462956:ios:00cce6034610ca79f47049',
    messagingSenderId: '604640462956',
    projectId: 'scmu-2ac12',
    databaseURL: 'https://scmu-2ac12-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scmu-2ac12.appspot.com',
    iosBundleId: 'com.example.scmu',
  );
}
